---
- block:
    - name: "Remove installed docker packages"
      raw: apt-get remove docker docker-engine docker.io containerd runc -y
      become: true
      become_user: root
      become_method: sudo
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Update and upgrade apt
      apt:
        upgrade: yes
        update_cache: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install needed packages
      raw: apt-get install apt-transport-https ca-certificates curl gnupg lsb-release git vim make
      become: true
      become_user: root
      become_method: sudo
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Add docker offical key
      raw:  curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      become: true
      become_user: root
      become_method: sudo

    - name: Fetch official repository
      raw: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      become: true
      become_user: root
      become_method: sudo

    - name: Install docker engine
      raw: apt-get update && apt-get install docker-ce docker-ce-cli containerd.io
      become: true
      become_user: root
      become_method: sudo

  tags:
    - install-docker
